### ISSUE TITLE
Why I cant see Real Ads!!

### ISSUE THREAD

**Issue by uniquegamesgr** [Shin-NiL/Godot-Android-Admob-Plugin#205]
@Shin-NiL, I am afraid to announce you that it has been a lot!!

Let me share my devastating story:

I have created a game with godot and implemented ADS using YOUR plugin. The code works fine, the game works fine, and I can only see test ads despite the fact that i use my own Unit IDs! Before you ask the "common questions" let me tell you that YES! I HAVE FOLLOWED EVERY LETTER OF YOUR INSTRUCTIONS!!! I AM USING GODOT 3.4.5 AND THE PLUGIN VERSION WHICH WORKS FOR IT!!! Firstly, i thought that it was just because it was not submitted on any stores or not approved by admob. So one day I set IS_REAL to TRUE and then i exported the .aab file without using EXPORT WITH DEBUG! I published my game on play store, it got approved, i added the store listing on admob as well! After it was approved from admob too, i set up the APP-ADS.TXT,  and then i peacefully waited for weeks in order for admob to show real ads. 

GUESS WHAT?

REAL ADS NEVER SHOWED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Since then, i have tried every solution possible, i have made a research for DAYS and didn't find anything helpful!
I checked all the games at the showcase and found out that only 2 games have real ads!

And so i do ask you: ME (A 19 YEAR OLD DEVELOPER WITH THE LEAST CODING EXPERIENCE) ASK YOU (A PROGRAMMER WITH PROBABLY A DEGREE, EXPERIENCE AND A PLUGIN FOR A GAME ENGINE) 

WHY THE FUCK I CANT SEE REAL ADS IN MY FREAKING GAME!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

WHY?
WHY?
WHY?

I HAVE LOST SO MUCH TIME AND ENERGY FOR A STUPID MISTAKE THAT NOBODY CAN FIND OUT !!!!!!!!!!!!!!!!!!!!!!!!!

AND AS A PROUD PROGRAMMER I EXPECT YOU TO ANSWER @Shin-NiL 

I EXPECT YOU TO ANSWER!

(By the way if anybody else have any idea of what the fuck is happening, any ideas will be appreciated!)

**Comment by neverdieboy** [comment]
@uniquegamesgr Hey! Truly can understand your situation. I had same issue some time ago. I don`t know if I can help for 100%, but I can just tell how I solved this problem. 
First of all, I have checked if I put right imformatiom in AndroidManifest.
After this, if you have reinstalled plugin in your project - check again AndroidManifest, and change it, also reload AdMob node in project, due to strange reason, if you update or reinstall this plugin in project it does not work. So you need to delete AdMob node, and just add it to scene again. 
Also you can try to force value "is_real" to be true by default, in admob.gd, also you should check if age rate is the same as in admob account. 
And the last question did you test your app on different devices after publishing it? Or you downloaded it to the same device where you were testing it during development?

**Comment by uniquegamesgr** [comment]
*SOLVED*

I had to wait 11 days until I started making money!

Thanks for your time!

**Comment by bertangokalp** [comment]
How can I set true is_real in .gd file
