### ISSUE TITLE
Readme doesn't mention app id

### ISSUE THREAD

**Issue by jaloveast1k** [Shin-NiL/Godot-Android-Admob-Plugin#23]
**Godot version:**
3.2.1stable

**Issue description:**
Subj, where do you put app-id? Admob requires app-id, not just separate ads block ids.

**Comment by Shin-NiL** [comment]
We are using play service ads 16.0.0, so app-id is not needed.

**Comment by cgeadas** [comment]
Isn't 16 deprecated/grey-listed?
As I mentioned in another issue, Google says "The following APIs are grey-listed and Google can’t guarantee that they will work on existing versions of Android. Some may already be restricted for your target SDK".
Why not use a newer api and avoid this potencial problems? Just because it works today doesn't mean it's good.

**Comment by jaloveast1k** [comment]
It seems that the real ads aren't displaying anymore. Test ads are working just fine (both rewarded and inter), but once you switch to real ones - nothing. Infinite error code 3 (no fill). 
Guess that's because the lib is outdated? Will test the same ids on a native Android app tomorrow.

**Comment by jaloveast1k** [comment]
Nah that's not the case, receiving the same result on a native android app with latest play-services-ads and app-id specified. Sorry :)

**Comment by cgeadas** [comment]
You can try on another equipment.
With me, I kept receiving error 3 for days (maybe a week) on my main equipment while, on others was working. Couldn't understand why.

**Comment by Shin-NiL** [comment]
> Why not use a newer api and avoid this potencial problems? Just because it works today doesn't mean it's good.

I have plans to update to a newer version, it's not hard at all, I just did not have free time to do that yet.
