### ISSUE TITLE
Call to load_banner() function shows banner without calling show_banner() function

### ISSUE THREAD

**Issue by bob333** [Shin-NiL/Godot-Android-Admob-Plugin#34]
**Godot version:**
3.2.1
**Admob Plugin version:**
3.0.1
**Issue description:**
$Admob.load_banner() call loads and shows the banner ad without calling the show_banner() function.

Its counter part $Admob.load_interstitial() only loads as expected. This issue is only with the banner ads.

**Comment by Shin-NiL** [comment]
Yeah, it's strange, but is the expected behavior, as described in the API Reference (readme):
```
# Load the banner (and show inmediatly)
load_banner()
```
In fact banner doesn't have (and doesn't need) a load, it's simply showed as called. Maybe remove the load function is a good idea, I really don't know.

One workaround you can use is to hide the banner as soon as it is loaded using the `banner_loaded` signal.
