### ISSUE TITLE
Rotate banner

### ISSUE THREAD

**Issue by bitmagine** [Shin-NiL/Godot-Android-Admob-Plugin#96]
**Godot version:**
3.2.3
**AdMob Plugin version:**
4.x
**Issue description:**
Hi! Thanks a lot for this awesome plugin =)

Is it possible to rotate the banners to place them on the side when the game is in landscape mode?
  
.

**Comment by Kamyabnz** [comment]
Do you mean on the left and right side of the screen in landscape mode?

**Comment by Shin-NiL** [comment]
You can change the size and position of the banner after you rotate the screen, in fact the demo does it. The method you can use is

```
# Resize the banner (useful when the orientation changes for example)
banner_resize()
```

**Comment by bitmagine** [comment]
> ¿Quiere decir en el lado izquierdo y derecho de la pantalla en modo horizontal?
> 
> y los anuncios están en formato vertical, ¿verdad?

Yes.

**Comment by bitmagine** [comment]
> Do you mean on the left and right side of the screen in landscape mode?
> 
> and the ads are in a vertical format right?

Yes.

**Comment by Kamyabnz** [comment]
As @Shin-NiL has stated it Ads such as banners change their rotation after the screen changes its rotation too, so they will always be on the right place automatically. But they still are wide banners on the top and bottom side of the screen.

So follow the banner_resize() method and change the size when you have landscape screens.

But AdMob does not really like vertical ads, because as stated here: [AdMob Link](https://developers.google.com/admob/android/banner) ads are meant to be shown horizontally. In this class [Code](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/blob/aa0022a09fa074edb7c01f9eab35391b0a645310/admob-plugin/godotadmob/src/main/java/shinnil/godot/plugin/android/godotadmob/Banner.java#L148) Determines the screen width (less decorations) to use for the ad width.

The Plugin gets the width and height from AdMob, so at the end of the day, you need a custom Adviewer that forces there size. What banner_resize() does as far as I understand, it tries to get bigger banners when the screen width gets bigger. Move method changes only the position from top to bottom.

So I am not sure if you will be able to get your ads Vertically on left and right of your screen in landscape mode. For that @Shin-NiL has an option to completely focus how the viewer gets the banner size and forces it fit somehow. Here they discuss the same problem [Problem](https://groups.google.com/g/google-admob-ads-sdk/c/mIFArc9mPR4?pli=1).

I hope this has clarifyed a bit on the problem at hand 😊

**Comment by bitmagine** [comment]
Thank you very much for the explanation.

**Comment by Shin-NiL** [comment]
Vertical banners are not supported, sorry.

**Comment by bitmagine** [comment]
> As @Shin-NiL has stated it Ads such as banners change their rotation after the screen changes its rotation too, so they will always be on the right place automatically. But they still are wide banners on the top and bottom side of the screen.
> 
> So follow the banner_resize() method and change the size when you have landscape screens.
> 
> But AdMob does not really like vertical ads, because as stated here: [AdMob Link](https://developers.google.com/admob/android/banner) ads are meant to be shown horizontally. In this class [Code](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/blob/aa0022a09fa074edb7c01f9eab35391b0a645310/admob-plugin/godotadmob/src/main/java/shinnil/godot/plugin/android/godotadmob/Banner.java#L148) Determines the screen width (less decorations) to use for the ad width.
> 
> The Plugin gets the width and height from AdMob, so at the end of the day, you need a custom Adviewer that forces there size. What banner_resize() does as far as I understand, it tries to get bigger banners when the screen width gets bigger. Move method changes only the position from top to bottom.
> 
> So I am not sure if you will be able to get your ads Vertically on left and right of your screen in landscape mode. For that @Shin-NiL has add a new option to completely focus how the viewer gets the banner size and forces it fit somehow. Here they discuss the same problem [Problem](https://groups.google.com/g/google-admob-ads-sdk/c/mIFArc9mPR4?pli=1).
> 
> I hope this has clarified a bit on the problem at hand 😊

Thank you very much for the explanation.

**Comment by bitmagine** [comment]
> Vertical banners are not supported, sorry.

What I intend is to put a horizontal banner (in landscape mode), but rotated and adapted to the screen height.

**Comment by Kamyabnz** [comment]
@bitmagine i will try out a solution and let you know how to switch top and button to left and right, but still horizontal. I don’t know how the google adMob policies are when it comes to showing horizontal ads in vertical form, just try to search for that.

I will let you know how your can do that kind of change in godot.

**Comment by Shin-NiL** [comment]
> I don’t know how the google adMob policies are when it comes to showing horizontal ads in vertical form, just try to search for that.

I don't think the advertiser and consequently Google would like that. I'm really sorry, but I won't do that.

**Comment by Kamyabnz** [comment]
@Shin-NiL I agree with you. @bitmagine you may have to change your concept when it comes to advertising on mobile. I have tried some concepts but it is impossible to move the banner to right and left and rotate them 90 degrees without changing the source code of the plugin. I would say that we cannot help you with this specific problem @bitmagine.

**Comment by bitmagine** [comment]
Okay.  Thank you all very much =)

**Comment by Kamyabnz** [comment]
Good luck mate 👍, so we can close this issue 😋
